coverage:
    status:
        project:
            default:
                target: 85%
                threshold: 10%
        patch:
            default:
                target: auto
                threshold: 50%
