language: java

os: linux
dist: yaketty
sudo: false

cache:
  directories:
  - $HOME/.m2

addons:
  apt:
    packages:
      - maven
      - gtk+3.0
      - stalonetray

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - rm ~/.m2/settings.xml

jdk:
  - oraclejdk8

script:
  - mvn clean package

after_success:
  - mvn jacoco:report coveralls:report
