language: java

os: osx
osx_image: xcode9.1
sudo: false

cache:
  directories:
  - $HOME/.m2

before_script:
  - brew install maven
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - rm ~/.m2/settings.xml

script:
  - mvn clean package

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 1edc2828-d9b8-4d0f-9407-31f4b583a663
