language: java

os: linux
dist: trusty
sudo: required

cache:
  directories:
  - $HOME/.m2

install: /bin/true

before_script:
  - "apt-get install -qq -o=Dpkg::Use-Pty=0 -y maven gtk+3.0 stalonetray ubuntu-gnome-desktop chromium-browser"
  - "touch ~/.stalonetrayrc"
  - "export DISPLAY=:99.0"
  - "Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &"
  - "sleep 3"
  - "stalonetray &"
  - "sleep 3"
  - "rm ~/.m2/settings.xml"

jdk:
  - oraclejdk8

script:
  - mvn clean package

after_success:
  - bash <(curl -s https://codecov.io/bash)
